version: '3'

tasks:

  dev:build:
    cmds:
      - docker compose -f ./tools/docker-compose.yml build

  dev:up:
    cmds:
      - docker compose -f ./tools/docker-compose.yml up -d  --remove-orphans

  dev:down:
    cmds:
      - docker compose -f ./tools/docker-compose.yml down

  dev:cli:
    cmds:
      - docker compose -f ./tools/docker-compose.yml exec --user astro core /bin/bash

  prod:build:
    cmds:
      - docker build -f tools/Dockerfile --target prod -t ember-nexus-api-docs:latest .

  prod:run:
    cmds:
      - docker run -p 80:80 ember-nexus-api-docs:latest

  swagger:generate:
    cmds:
      - find ./core/src/data/swagger -name '*.json' -print0 | sort -z | xargs -0 jq -s 'reduce .[1:][] as $x (.[0]; . * $x)' > ./core/src/data/swagger.json
