import { h } from "hastscript";
import { visit } from "unist-util-visit";

// --- minimal local hast/vfile types (avoids depending on @types/hast) ------

type Properties = Record<string, unknown>;

interface Element {
  type: "element";
  tagName: string;
  properties: Properties;
  children: ElementContent[];
  position?: { start?: { line?: number } };
}

interface Root {
  type: "root";
  children: ElementContent[];
}

interface Text {
  type: "text";
  value: string;
}

// Permissive catch-all: the real hast tree also contains comment / doctype /
// text / raw nodes, so this keeps it assignable to the minimal types above.
type ElementContent = Element | Text | { type: string; [key: string]: unknown };

interface File {
  path?: string;
}

// -----------------------------------------------------------------------

const ICON_PATHS: Record<string, string> = {
  "arrow-right": "M5 12h14M12 5l7 7-7 7",
  "arrow-up-right": "M7 17L17 7M7 7h10v10",
};

function makeIconNode(name: string): ElementContent {
  return h(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      "stroke-width": "2",
      "stroke-linecap": "round",
      "stroke-linejoin": "round",
      class: "link-icon",
    },
    [h("path", { d: ICON_PATHS[name] })],
  );
}

function isBrokenHref(href: string): boolean {
  const normalized = href.trim().toLowerCase();
  return normalized === "" || normalized.includes("todo");
}

export function isExternalHref(href: string): boolean {
  const trimmed = href.trim();

  // Protocol-relative URLs → external
  if (trimmed.startsWith("//")) return true;

  // Has an explicit scheme (e.g. https://) → external; otherwise relative → internal
  return /^[a-zA-Z][a-zA-Z\d+\-.]*:/.test(trimmed);
}

export function linkAugmentation() {
  return (tree: Root, file: File): void => {
    visit(
      tree,
      "element",
      (
        node: Element,
        index: number | undefined,
        parent: Element | Root | undefined,
      ) => {
        if (node.tagName !== "a") return;

        // Footnote reference/backreference links (generated by remark-gfm from
        // `[^label]` syntax — see `mdast-util-to-hast`'s footnote handlers) get
        // their own minimal styling in CSS instead of the arrow-icon treatment
        // every other link gets here.
        if (
          node.properties?.dataFootnoteRef !== undefined ||
          node.properties?.dataFootnoteBackref !== undefined
        ) {
          return;
        }

        const href = node.properties?.href as string | undefined;
        if (href === undefined) return;

        const broken = isBrokenHref(href);
        const isExternal = isExternalHref(href);
        const iconName = isExternal ? "arrow-up-right" : "arrow-right";

        if (broken) {
          node.properties = {
            ...node.properties,
            style: "color: red;",
          };

          const filePath = file?.path ?? "unknown file";
          const line = node.position?.start?.line;
          const location =
            line !== undefined ? `${filePath}:${line}` : filePath;
          // Intentional build-time diagnostic — surfaces broken/placeholder
          // links in the terminal during `astro build`.
          // eslint-disable-next-line no-console
          console.warn(
            `[linkAugmentation] Broken/placeholder link (href="${href}") at ${location}`,
          );
        }

        // Wrap icon in a no-break span to prevent gap+icon from orphaning onto its own line
        node.children = [
          ...node.children,
          h("span", { class: "link-icon-wrap" }, [makeIconNode(iconName)]),
        ];

        // The MDX/JSX compilation step that follows (hast -> estree) drops
        // whitespace that immediately follows this element once it ends in the
        // freshly-appended <svg> icon - "[link](url) word" (or a link followed
        // by a soft line break, i.e. the connecting word starts the next
        // source line) renders as "linkword" with the whitespace silently
        // eaten. A non-breaking space survives that step (it isn't collapsible
        // whitespace), so swap the sibling text's leading whitespace run for
        // one instead of losing it outright.
        if (
          index !== undefined &&
          parent &&
          "children" in parent &&
          parent.children[index + 1]?.type === "text"
        ) {
          const nextText = parent.children[index + 1] as Text;
          if (/^\s/.test(nextText.value)) {
            nextText.value = "\u00A0" + nextText.value.replace(/^\s+/, "");
          }
        }

        if (isExternal) {
          node.properties.target = "_blank";
          node.properties.rel = "noopener noreferrer";
        }
      },
    );
  };
}
